### ISSUE TITLE
Logo is off at small screen sizes

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/juju.is#11]
Reduce viewport to 500px

<img width="568" alt="Screenshot 2019-11-01 at 11 12 19" src="https://user-images.githubusercontent.com/505570/68021532-8c90b380-fc99-11e9-868d-28592fbd6ac5.png">

**Comment by anthonydillon** [comment]
Thanks @barrymcgee. Will get on this next week.
