### ISSUE TITLE
Juju logo colour inverts when scrolling on Discourse

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/juju.is#132]
When viewing a post on Discourse the logo is:

![Screen Shot 2020-09-23 at 11 21 28 AM](https://user-images.githubusercontent.com/532033/94047167-f244cd00-fd8e-11ea-96c7-802997dd7a3c.png)

After scrolling:

![Screen Shot 2020-09-23 at 11 20 30 AM](https://user-images.githubusercontent.com/532033/94047187-f8d34480-fd8e-11ea-9dcf-0ece8402037a.png)

**Comment by anthonydillon** [comment]
Jeff, can you try hard refresh?

**Comment by hatched** [comment]
Yep looks like a caching issue, sorry about that.
