### ISSUE TITLE
Report a bug link goes to charmhub

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/juju.is#146]
Update the report a bug link.

**Comment by barrymcgee** [comment]
@anthonydillon Where is this link?

The 'Report a bug on this site' in the footer on juju.is correctly points to https://github.com/canonical-web-and-design/juju.is/issues/new

**Comment by anthonydillon** [comment]
@barrymcgee thanks for looking into this. Looks like it's right. Sorry, don't know what this is referring too.
