### ISSUE TITLE
[Discourse] When scrolling down header buttons become inoperable

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/juju.is#153]
See: https://discourse.juju.is/t/when-scrolling-down-header-buttons-become-inoperable/3708

> Summary:
> Scrolling down on any page disables the header buttons from functioning. Interestingly, the tripple-bar menu and search icons are clickable, as well as the “Discourse” link on the header, but nothing under the menu icon works.
> 
> Not sure if this applies to solely the Juju discourse or all Canonical hosted Discourse pages.
> 
> Environment:
> Chrome version 84.0.4147.135 installed via the snap
> 
> Steps to reproduce:
> 
>     Scroll the page down from the top until the header transitions.
>     Click on any button such as “Login”
> 
> Expected result:
> The click is registered and you navigate to the selected page.
> 
> Actual result:
> The button does not highlight and the click is not registered.

**Comment by hatched** [comment]
QA OK!

**Comment by anthonydillon** [comment]
@hatched Thanks.
