### ISSUE TITLE
Ascii cinema doesn't render on intro tutorial

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/juju.is#167]
https://juju.is/docs/getting-started-with-juju has an ascii cinema video, but it doesn't render correctly. I simply see a broken image.

**Comment by nottrobin** [comment]
Thanks Tom. This is actually a duplicate of https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/76. Well, you might have filed yours first, but that one has more explanation =)

Basically, the URL has to be absolute, not relative, to work when it's pulled into the docs platform. We're hoping to make this more robust.
