### ISSUE TITLE
`juju deploy postgresql` from hello juju tutorial fails with 2.9-rc3-focal-amd64

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/juju.is#168]
I'm running juju 2.9-rc3-focal-amd64. On https://juju.is/docs/getting-started-with-juju it instructs you to run `juju deploy postgresql` but I get the following error:

```
Located charm "postgresql" in charm-hub, revision 215
ERROR unrecognized charm schema "ch"
```

**Comment by SimonRichardson** [comment]
Unfortunately, this is a juju bug, we're currently working on this as we speak. We hope to get a new version of Juju out in the next couple of weeks.

**Comment by SimonRichardson** [comment]
Juju `2.9-rc4` is now in the `latest/candidate` that will hopefully fix this issue.
Let me know if you get any issues.

**Comment by mthaddon** [comment]
I'm getting an error with this which I understand is due to a problem with the charmhub api:

https://paste.ubuntu.com/p/3F6D4RCxxT/

**Comment by SimonRichardson** [comment]
@mthaddon you are correct. Essentially we've settled on the hash naming throughout the API that was previously inconsistent. That has now been fixed on the staging API, which needs to be pushed to the production API.

**Comment by anthonydillon** [comment]
This issue is still valid. I am getting the same issue. Will test again in a few days.

**Comment by SimonRichardson** [comment]
If you target the staging server this works as expected...

```
juju add-model test --config charmhub-url="https://api.staging.snapcraft.io"
```

**Comment by cristinadresch** [comment]
@SimonRichardson Is there a bug in juju that we can add here for reference? So we can close this one here, thanks

**Comment by SimonRichardson** [comment]
This should work now, so we should close it

**Comment by anthonydillon** [comment]
Confirmed this is now resolved :+1:
