### ISSUE TITLE
Searching for 'charm hooks' pulls up mostly broken links

### ISSUE THREAD

**Issue by aieri** [canonical-web-and-design/juju.is#172]
This search:
https://juju.is/docs/search?q=charm+hooks

Produces these links (first page):
[BROKEN] https://juju.is/docs/charm-hooks
[BROKEN] https://juju.is/docs/charm-writing/hook-errors
[BROKEN] https://juju.is/docs/charm-writing/hook-debug
[BROKEN] https://juju.is/docs/charm-writing/hook-env
[WORKS] https://juju.is/docs/charm-writing
[BROKEN] https://juju.is/docs/writing-your-first-juju-charm
[WORKS] https://juju.is/docs/charm-writing/hook-tools
[BROKEN] https://juju.is/docs/components-of-a-charm
[WORKS] https://juju.is/docs/glossary
[BROKEN] https://juju.is/docs/event-cycle

**Comment by anthonydillon** [comment]
Google has re-index
