### ISSUE TITLE
Side Navigation for Docs pages

### ISSUE THREAD

**Issue by jnsgruk** [canonical-web-and-design/juju.is#189]
Hi team :wave: 

It would be great if the table of contents feature from Discourse was replicated on published docs pages. 

See image below where the headings are automatically put into a little floating content bar on the right that follows the users scroll.
![screen-1](https://user-images.githubusercontent.com/668505/115013104-8fd92880-9ea8-11eb-939f-c1d63d4315fa.png)

It would be awesome to have the same feature on the actual docs pages at https://juju.is/docs/sdk:
![screen-2](https://user-images.githubusercontent.com/668505/115013207-aa130680-9ea8-11eb-9f57-f7446909a1f4.png)

Thanks!

**Comment by fitojb** [comment]
This can be achieved through the use of the Table of Contents component of the Vanilla Framework

**Comment by jnsgruk** [comment]
Oh, as is I can include something in the doc source that will do it now?

Or just a future implementation could use that component?

**Comment by fitojb** [comment]
No, this needs further development on the discourse parser.

**Comment by tbille** [comment]
As @fitojb this is a great idea.  We should have a discussion with the Vanilla team.

**Comment by Lukewh** [comment]
This seems outdated now, but updates are coming to improve documentation hierarchy this cycle (22.10). It appears most people (but not me) were aware of these upcoming changes, and the people that need to be in contact are in contact. I'm going to close this issue as there will be more specific and up-to-date issues created!
