### ISSUE TITLE
Images in "What Is Juju" Section Cover Text

### ISSUE THREAD

**Issue by j5awry** [canonical-web-and-design/juju.is#231]
Browser: Firefox 88.0

While scrolling, through "What Is Juju", the graphic size of the "Hybrid Cloud" graphic increases beyond the column boundary. This puts the graphic over the text. 
![Screenshot from 2021-05-05 10-33-51](https://user-images.githubusercontent.com/8875872/117168104-7b909900-ad8d-11eb-8acf-2f6c20326dd5.png)

**Comment by anthonydillon** [comment]
@j5awry thanks for the report. I see you have decreased your font size in your browser. Is it something the animation does not support at the moment. I will work on providing that support.
