### ISSUE TITLE
Bubbles on tutorials issue

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/juju.is#239]
![image](https://user-images.githubusercontent.com/2707508/117987270-3abaf600-b332-11eb-9962-1f7f13d5342c.png)

See tutorial:
https://juju.is/tutorials/deploy-nextcloud-and-collabora-on-ubuntu#1-introduction

**Comment by fitojb** [comment]
Confirmed. Similar to this: https://github.com/canonical-web-and-design/ubuntu.com/issues/6547

**Comment by tbille** [comment]
@lyubomir-popov Could it be related with a Vanilla update?

**Comment by lyubomir-popov** [comment]
@tbille the markup on this page differs from the official example: https://vanillaframework.io/docs/examples/patterns/lists/lists-stepped
you need to use a title, the component currently doesn't support a paragraph.

**Comment by lyubomir-popov** [comment]
Reported here: https://github.com/canonical-web-and-design/vanilla-framework/issues/3748
