### ISSUE TITLE
redirects from SDK docs 404

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/juju.is#258]
The website seems to be rewriting urls incorrectly from the docs navigation. 

E.g. on [this sdk docs page](https://juju.is/docs/sdk)

the navigation section of the source document for the site includes the following:
```
...
| 0 | | Reference |
| 1 | github | [Github](https://github.com/canonical/operator) |
| 1 | api-docs | [API Documentation](https://ops.rtfd.io) |
```
However, neither of these links are translated properly by the website. E.g:

```
 https://github.com/canonical/operator -> https://juju.is/canonical/operator
 ```

**Comment by jkfran** [comment]
Thank you for reporting the issue, it is a bug in the documentation parser.
