### ISSUE TITLE
"Get help" links from SDK docs incorrect

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/juju.is#261]
On https://juju.is/docs/sdk there's a "Get Help" section. The "Community Discourse" text isn't a link to anything, and "Community Chat" links to https://juju.is/charmhub/channels/juju which 404s.

**Comment by jkfran** [comment]
Thank you for the report Tom, it seems to be a duplicate of https://github.com/canonical-web-and-design/juju.is/issues/258

There is a PR in the review process for it

**Comment by jkfran** [comment]
It should be all good now, let me know if not :)
