### ISSUE TITLE
Links in storage table of contents don't work

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/juju.is#268]
Visiting https://juju.is/docs/olm/defining-and-using-persistent-storage there's a table of contents at the top. It includes links like https://juju.is/docs/olm/defining-and-using-persistent-storage#storage-management-commands but that doesn't actually take you to the relevant section.

**Comment by jkfran** [comment]
I fixed those links on the Discourse topic
cc: @pedroleaoc
