### ISSUE TITLE
Dilbert image is cropped on k8s report

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/juju.is#275]
On https://juju.is/cloud-native-kubernetes-usage-report-2021

https://user-images.githubusercontent.com/2376968/123129581-f730cd00-d443-11eb-976b-d761aca24549.png

See: https://docs.google.com/document/d/1PEcz_9tFvzrvX5U5pBQFqHKC_0wfb8wtE6KD9HEa_Ls/edit?disco=AAAAM0-CHks

**Comment by pmahnke** [comment]
Winner of best bug report of 2021🎉
