### ISSUE TITLE
Easier method for linking to subheadings

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/juju.is#303]
It would be nice if there was a way to link to a heading in a docs page - e.g. I've just said to someone in https://chat.charmhub.io/charmhub/channels/charm-dev: 

"""see the "Peer relation example" section of https://juju.is/docs/sdk/relations."""

The link already exists, as https://juju.is/docs/sdk/relations#heading--peer-relations but it is a bit hidden. To find that you have to right click the header -> inspect element -> look the HTML code for the id tag. It'd be nice if there was a visual element that let you copy that link.

**Comment by jkfran** [comment]
There is no option for this right now as we show the HTML as it is from Discourse.

I think the best place for this issue might be https://github.com/canonical-web-and-design/canonicalwebteam.discourse/ . I created an issue https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/105 for it.
