### ISSUE TITLE
[note type=important] not behaving as expected

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#329]
Noticed that [note type=important] doesn't alter the text in any way, as opposed to [note status="..."], which actually sets it off in a box.

**Comment by degville** [comment]
This is also a problem with the snapcraft documentation, as seen on https://snapcraft.io/docs/documentation-guidelines:

![Screenshot_20210916_154820](https://user-images.githubusercontent.com/7047542/133633999-1425e544-8e24-4bce-b7a9-a04818785c08.png)

**Comment by anthonydillon** [comment]
Sorry about this, seems we moved away from using "important" as a type of notifications. We have:
- Information
- Caution
- Positive
- Negative

[Vanilla documentation](https://vanillaframework.io/docs/patterns/notification#severity-levels). 

We should have communicated this change more widely. I hope its not to much trouble to migrate to this set of types. 

This is process discussion we should has as Vanilla team. cc: @bartaz @lyubomir-popov @sowasred2012

**Comment by cristinadresch** [comment]
@tmihoc if you need more information for this let us know
