### ISSUE TITLE
"Understanding Kubernetes charms - tutorial" leads to 500

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/juju.is#330]
[This page](https://juju.is/docs/t/understanding-kubernetes-charms-tutorial/1263) returns a 500 server error. I assume it should be showing a page generated from [this discourse topic](https://discourse.charmhub.io/t/understanding-kubernetes-charms-tutorial/1263).

We should investigate.

**Comment by cristinadresch** [comment]
@nottrobin can you check that page again? it seems to be working fine noe

**Comment by nottrobin** [comment]
Yep, thanks.
