### ISSUE TITLE
On juju.is, a couple of typos in the diagrams

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#344]
On https://juju.is/, in the diagrams: 

- "Kubeneted" should be "Kubernetes" (with "r", and with "s" instead of "d")
- "Microk8s" should be "MicroK8s" (capital "K")

**Comment by waynecrosby** [comment]
@hatched Attached are the updated SVGs, I think it is only in these 2 and they are repeated throughout the animation...
[New Juju frames.zip](https://github.com/canonical-web-and-design/juju.is/files/7538692/New.Juju.frames.zip)

**Comment by anasereijo** [comment]
@steverydz is this something you can do?

**Comment by steverydz** [comment]
@anasereijo yes I can replace them

**Comment by steverydz** [comment]
@waynecrosby @anasereijo there is also this one that needs updating https://assets.ubuntu.com/v1/7b84cf45-what-is-juju-illustration-5.svg

**Comment by waynecrosby** [comment]
@steverydz Thanks, I'll take a look

**Comment by anasereijo** [comment]
@steverydz can we close this?

**Comment by steverydz** [comment]
@anasereijo it's not fixed still

**Comment by anasereijo** [comment]
@waynecrosby can you send us the assets, please?

**Comment by waynecrosby** [comment]
@anasereijo Will get to it next week, thanks :)

**Comment by tmihoc** [comment]
Insofar as I can see, these haven't been fixed yet.

![image](https://user-images.githubusercontent.com/38667005/166706293-378bd685-def7-49b8-b979-ef55be274ad8.png)

**Comment by tmihoc** [comment]
Hi @cristinadresch , I see this is marked closed, but the issue isn't fixed. If at all possible, it would be great if we could fix it before 1 PM CEST today.

**Comment by anthonydillon** [comment]
I am not sure why is this closed, likely by mistake. I will reopen until the asset can be recreated.

**Comment by waynecrosby** [comment]
@steverydz Attached is the updated SVG, let me know if you have any issues with it...
![what-is-juju-illustration-5-updated](https://user-images.githubusercontent.com/42238722/169565928-509fd86c-5bdf-4b34-91f1-374922cf504d.svg)

**Comment by steverydz** [comment]
@waynecrosby could you do a version that has the blank space on top? All the others have a transparent gap, see example: https://assets.ubuntu.com/v1/13433375-what-is-juju-illustration-1.svg

**Comment by waynecrosby** [comment]
@steverydz It's been a real pain as the SVG kept shifting for some reason. Anyway, I've used 4 as a base and attached both versions her, hopefully they work ok, let me know if not...
![what-is-juju-illustration-4-updated](https://user-images.githubusercontent.com/42238722/172860092-b104bb78-0de5-46c8-b4a7-c72eef8679d3.svg)
![what-is-juju-illustration-5-updated](https://user-images.githubusercontent.com/42238722/172860118-69ed586d-0ab2-409f-a54b-b60ed7dafa95.svg)
