### ISSUE TITLE
On juju.is, discourse.charmhub.io, search doesn't find/display results from details.

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#352]
E.g., consider this juju.is doc and its Discourse variant: https://juju.is/docs/olm/get-started-on-kubernetes#heading--gaining-access-to-a-kubernetes-cluster and https://discourse.charmhub.io/t/get-started-on-kubernetes/1090 .

In this doc, "add-k8s" appears twice, in the details under " Manually exposing the cluster's configuration file" and in the details under "When you have used Juju to deploy Charmed Kubernetes".

However, if I search for "add-k8s", on juju.is it finds 0/0 results, and on Discourse it finds 2/2 but doesn't expand the details to show it to you (the text is highlighted but you have to manually expand the details to see that).

**Comment by jkfran** [comment]
Hi, It is strange but I think the issue was solved by wiping the cache. On juju.is we use google as the search engine behind the scenes and maybe the search was done before the content was there?

Please let me know if it is fine now to close this issue.

**Comment by tmihoc** [comment]
On my end both issues persist.

**Comment by jkfran** [comment]
@tmihoc I think the search is working as it is supposed to:

**On Discourse:**
Search URL: https://discourse.charmhub.io/search?q=add-k8s
One of the results:
![image](https://user-images.githubusercontent.com/6353928/139834025-48b4efc1-5abe-417d-a842-142b0c989783.png)

**On Juju.is:**
Search URL: https://juju.is/docs/search?q=add-k8s
One of the results:
![image](https://user-images.githubusercontent.com/6353928/139834366-6ba83532-7c5a-4075-a2fe-76868da2079f.png)

In this case, the word `add-k8s` is not highlighted.

**Comment by tmihoc** [comment]
Let me revise my original statement of the issue: What I meant by search was a simple search with Ctrl+F on the page. Insofar as I can see, that continues to fail as I've described.

**Comment by jkfran** [comment]
Hi @tmihoc,

On juju.is, unfortunately, hidden content can't be searched by `Ctrl+F`. If you prefer maybe you can remove the `[details]` tags on that Discourse topic so we display the content always.

I can see the issue now searching on the Discourse topic as well but we can't alter how it works either, it should be an issue for Discourse developers.

The best solution, if you are really concerned about this, is to remove the `[details]` tags.

I am going to close this issue as it can't be solved.
