### ISSUE TITLE
Learn menu different on juju.is vs. charmhub.io

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#353]
On https://juju.is/ it shows like this, with Documents and Resources:

![image](https://user-images.githubusercontent.com/38667005/139420957-67c07b31-a990-4809-a4f2-e1d982305cac.png)

On https://charmhub.io/ it shows like this, with Documents but not Resources:

![image](https://user-images.githubusercontent.com/38667005/139421014-3693e15f-6ca5-41a1-bebc-1dc9ab7ec250.png)

Recommendation: Since the intention seems to be for these menus to be identical, add Resources to the Charmhub Learn menu also.

**Comment by tmihoc** [comment]
In case it's relevant: The menu on [discourse.charmhub.io](https://discourse.charmhub.io/) is still different:
![image](https://user-images.githubusercontent.com/38667005/211518083-34ee1af6-1465-44f6-91ea-648f3aef82bf.png)

**Comment by steverydz** [comment]
@tmihoc Thanks. I've updated the content of that menu now so it matches the websites. We're looking at the discourse nav separately so they will be updated visually hopefully soon.
