### ISSUE TITLE
Discourse parallel raw/rendered scroll isn't really parallel

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#357]
For example,

https://discourse.charmhub.io/t/using-gitlab-as-a-container-registry-for-kubernetes/2642

![image](https://user-images.githubusercontent.com/38667005/139635731-54074808-4e70-4758-a112-d0c0fcd80d45.png)

As a result, it's not as helpful as it could be.

**Comment by anthonydillon** [comment]
Unfortunately this is a issue with the discourse preview. This is due to hidden content (in this case front matter) rending in the raw but of course hidden in the preview. Might be something to bring up in https://meta.discourse.org.
