### ISSUE TITLE
Put tutorials table of contents on tutorials web page

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#364]
On the Juju website there is a page dedicate just to tutorials: https://juju.is/tutorials

Its table of contents is however located in an undiscoverable place on Discourse: https://discourse.charmhub.io/t/the-tutorials-on-juju-is/2628

I know [the instructions for how to publish a tutorial simply say to send it to Canonical editors](https://juju.is/tutorials/how-to-write-a-tutorial#9-review-and-publishing-process). However, it's unclear to me (and others I've heard from) why people can publish to Discourse directly but not here. I think it would be best if the process for publishing (and the outcome...) looked the same.

**Comment by anthonydillon** [comment]
I am unsure of the request here. Are you suggesting we should allow users to add tutorials themselves to the index topic as a method of listing tutorials? The purpose as stated in the publishing guide is to gate the published tutorials for review and QA purposes.

**Comment by jameinel** [comment]
I think the question is that on most Docs pages, we have the "Discuss this in the Forum" link that leads you back to the original post. Which is usually very helpful for figuring out how the two are linked.
Eg on: https://juju.is/docs/olm there is the link: [Help improve this document in the forum.](https://discourse.charmhub.io/t/the-charmed-operator-lifecycle-manager-olm-docs/1087)

It is odd that this doesn't also appear on
https://juju.is/tutorials

I can understand if we want to have a Review style workflow for tutorials, but it also seems strange that tutorials are held to a different standard than the rest of the docs.

**Comment by anthonydillon** [comment]
I see, I assume this is mainly for maintainers of the site. As we don't want to encourage user edits to the index topic. I guess we could either:
1. add a link to the index topic on the tutorials landing page but I worry that might confuse users.
2. add a section to the [publishing section of the guide](https://juju.is/tutorials/how-to-write-a-tutorial#9-review-and-publishing-process) and explain this is for site admins only.

Would either of this approaches resolve this confusion?

**Comment by tmihoc** [comment]
I think 1 fits better with how [the OLM docs](https://juju.is/docs/olm) and [the SDK docs](https://juju.is/docs/sdk) are now, but 2 fits better with how https://juju.is/tutorials is now. So for now maybe let's go with 2. But, in the long run, I'd also like to revisit the reasons why we keep 
these tutorials so separate from the rest of the documentation, which now (since Diataxis) already contains a section for tutorial-type materials (see, e.g., [the OLM docs](https://juju.is/docs/olm)).

**Comment by Lukewh** [comment]
Agreed solution:
Link to the tutorial index page on discourse from the [publishing section of the guide](https://juju.is/tutorials/how-to-write-a-tutorial#9-review-and-publishing-process)

**Comment by Lukewh** [comment]
Final sentence added with link.
![image.png](https://images.zenhubusercontent.com/59316f3551aa2c3057803f4b/e2b5383b-f149-483d-ab6e-701a3ac70dce)
