### ISSUE TITLE
Missing page - "Constraints details"

### ISSUE THREAD

**Issue by mkalcok** [canonical-web-and-design/juju.is#365]
Page with url https://juju.is/docs/olm/constraints-detailed is missing. This page is linked from [here](https://juju.is/docs/olm/constraints) (first paragraph) and should contain list of constraints that can be defined for juju machine.

**Comment by anthonydillon** [comment]
Both links result in 404 for me. It appears the new page is: https://juju.is/docs/olm/manage-constraints which all links seem to work. Please reopen if the issue persists.

**Comment by mkalcok** [comment]
> Both links result in 404 for me

This is strange, the second link https://juju.is/docs/olm/constraints still works for me, I even tried restarting browser to make sure it's not some weird caching issue.
I'm including screenshot that shows "docs/olm/constraints" page loaded with link to the broken "docs/olm/constraints-detailed" (hovered)

<img width="2032" alt="Screenshot 2021-11-19 at 15 12 23" src="https://user-images.githubusercontent.com/69471063/142636428-8786289d-9051-495c-bc49-402065de6116.png">

**Comment by anthonydillon** [comment]
I get the same thanks for the link. We will investigate.

**Comment by mkalcok** [comment]
Just some more info I observed.
The loading of the https://juju.is/docs/olm/constraints page is hit or miss even on my end. I tried it for some time now and sometimes it loads and sometimes it throws `404`

**Comment by tmihoc** [comment]
Constraints (detailed) no longer exists. (It is now called [Constraints reference](https://juju.is/docs/olm/constraints-reference).) However, strangely, when I click on your link I see Constraints (detailed) too. Some caching issue. I've noticed many of this sort recently. PS More coming up as the work to restructure the documentation progresses (as it will often involve creating new posts and moving them around till things settle).

**Comment by Lukewh** [comment]
It seems like the issue is there is a link to a page that doesn't exist from a page that is deprecated.

Solution:
Automatically redirect https://juju.is/docs/olm/constraints to https://juju.is/docs/olm/constraint

**Comment by Lukewh** [comment]
@tmihoc great news! Shall we close this issue?

**Comment by tmihoc** [comment]
yes please, and thanks!

**Comment by Lukewh** [comment]
:partying_face:
