### ISSUE TITLE
Links to subheadings generate a title preview in Discourse editor but not on Discourse or juju.is

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#368]
When I edit, I see this, with a preview

![image](https://user-images.githubusercontent.com/38667005/144434403-7112d7a4-d178-4940-9a9e-dee0c933bf8d.png)

 But after saving I see this:

![image](https://user-images.githubusercontent.com/38667005/144434825-c1278539-5acd-41bd-9b76-a0f0fa953377.png)

PS It would also be nice if the title preview included the subheading, i.e., "Juju | Add credentials" | Use a YAML file . Right now it just says "Juju | Add credentials".

**Comment by tmihoc** [comment]
Also this on https://discourse.charmhub.io/t/manual-cloud/1095#heading--create-a-controller:

![image](https://user-images.githubusercontent.com/38667005/144466095-8a533b2e-194f-4c5b-a357-f316544d2b63.png)

**Comment by jkfran** [comment]
@tmihoc could you try using the markdown format for links: `[text](link)`
