### ISSUE TITLE
Console syntax highlighting in docs pages 

### ISSUE THREAD

**Issue by timClicks** [canonical-web-and-design/juju.is#37]
Our current syntax highlighting system doesn't distinguish between commands executed on the command line and their output. Compare with GitHub:

```console
$ juju add-machine
created machine 1
$ juju upgrade-series 0 prepare bionic
WARNING: This command will mark machine "0" as being upgraded to series "bionic".
This operation cannot be reverted or canceled once started.
Units running on the machine will also be upgraded. These units include:
  rabbitmq-server/0

Leadership for the following applications will be pinned and not
subject to change until the "complete" command is run:
  rabbitmq-server

Continue [y/N]? y
```
This makes it very hard to write nicely formatted tutorials.

[Sorry if this is the wrong place to lodge this!]

**Comment by matthewpaulthomas** [comment]
I think this requires two things:
1. our Vanilla CSS framework to distinguish between CLI input and output ([vanilla-framework#1549](https://github.com/canonical-web-and-design/vanilla-framework/issues/1549))
1. [our Discourse-to-docs converter](https://github.com/canonical-web-and-design/canonicalwebteam.discourse-docs) to automatically apply the new classes to the contents of any <code>```console</code> block.

**Comment by timClicks** [comment]
Thanks @matthewpaulthomas. Do you know if it's possible to trigger the [code / copyable](https://vanillaframework.io/docs/examples/patterns/code-copyable) and [code / numbered](https://vanillaframework.io/docs/examples/patterns/code-numbered) compontents via discourse-docs?

**Comment by anthonydillon** [comment]
We don't have code components modules in discourse yet. You could put the Mark up in discourse but I won't have the styling.

**Comment by cristinadresch** [comment]
@anthonydillon what do you think we should do about this one?

**Comment by anthonydillon** [comment]
@hatched when triaging an issue can you add a priority label please.

**Comment by anthonydillon** [comment]
@timClicks could you share an example please and I'll see what I can do

**Comment by steverydz** [comment]
This has been fixed here https://github.com/canonical-web-and-design/juju.is/pull/253
