### ISSUE TITLE
Indent table at same level as parent bullet point?

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#373]
Is there any way to indent a table at the same level as its parent bullet point?

![image](https://user-images.githubusercontent.com/38667005/146558580-af0a6613-e5d4-46fe-992c-373b227ba386.png)

**Comment by anasereijo** [comment]
@steverydz do you know if we can do this?

**Comment by steverydz** [comment]
@tmihoc If you structure the markdown like this you should be able to achieve what you're trying to do:

```
- Setup your cloud
  Juju can be run...
  | Kubernetes      | Localhost |
  | ----------- | ----------- |
  | MicroK8s      | LXD       |
```

**Comment by anasereijo** [comment]
thanks @steverydz! 

@tmihoc I will closed this now, please reopen if you have any issues with this :)

**Comment by tmihoc** [comment]
> @tmihoc If you structure the markdown like this you should be able to achieve what you're trying to do:
> 
> ```
> - Setup your cloud
>   Juju can be run...
>   | Kubernetes      | Localhost |
>   | ----------- | ----------- |
>   | MicroK8s      | LXD       |
> ```

I've tried this and the result is gibberish (the table format basically collapses). So I have to revert to my hack where I add an empty first column.
