### ISSUE TITLE
404 on link

### ISSUE THREAD

**Issue by solmyrcan** [canonical-web-and-design/juju.is#377]
Getting a 404 on the link "Hello, World" under "Charm your application"

**Comment by tmihoc** [comment]
This might have been my fault, as I unliked that doc from Navigation for a bit. It should be back on now---this works for me: https://juju.is/docs/sdk/hello-world .

**Comment by anthonydillon** [comment]
@solmyrcan thank you for taking the time to report this issue to us.

@tmihoc thanks for fixing it!
