### ISSUE TITLE
Collapsible navigation in docs

### ISSUE THREAD

**Issue by timClicks** [canonical-web-and-design/juju.is#38]
The Juju documentation is extensive. And, yet it has gaps. We would like to continue to expand it, but are worried about nesting navigation too deeply.

Would it be possible to toggle the visibility of (sub-)sections?

**Comment by spencerbygraves** [comment]
Hi @timClicks, we are currently building a new side navigation in the [Vanilla framework](https://github.com/canonical-web-and-design/vanilla-framework/issues). When that work is done we'll be able to update the docs to have collapsible sections.

**Comment by anthonydillon** [comment]
@hatched just need a priority on this one and triage is all good.

**Comment by anthonydillon** [comment]
We are moving away from collapsed navigation for docs sites.
