### ISSUE TITLE
Default fixed column width results in hard to read tables

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#380]
An example here: https://juju.is/docs/sdk/storage

Is there any way we can control the width?

**Comment by anthonydillon** [comment]
Hi @tmihoc, there are two options here.
1. We could update a global setting for the site to make all tables layout `auto`
2. Leave it as `fixed` by default and write that table as HTML with the class `u-table-layout--auto`

These options are documented here: https://vanillaframework.io/docs/settings/table-layout. It depends if you mind having all you docs tables become auto?

**Comment by tmihoc** [comment]
@jnsgruk What do you think?

**Comment by jnsgruk** [comment]
Can we take a look at a demo site with all set to auto? I can't think of a specific case where auto wouldn't be what we want? :)

**Comment by anthonydillon** [comment]
@jnsgruk @tmihoc Sure here is [the PR](https://github.com/canonical-web-and-design/juju.is/pull/381) and the demo can be found at https://juju-is-381.demos.haus/docs/sdk/storage

**Comment by jnsgruk** [comment]
Thanks @anthonydillon - yeh having a poke about through that page makes me think that this is a better default. Can we go ahead with this? :)

**Comment by anthonydillon** [comment]
Sure, once code approved. Will push this to production.

**Comment by tmihoc** [comment]
This definitely looks much nicer. Thanks! Looking forward to seeing it go live!
