### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by zeeshanali** [canonical-web-and-design/juju.is#386]
Juju was initially conceived in 2009 by Mark Shuttleworth, Gustavo Niemeyer and Simon Wardley [[1](https://blog.labix.org/2013/06/25/the-heart-of-juju)]   <---- this link is no longer working

source url: 
https://juju.is/docs/sdk/history

**Comment by anthonydillon** [comment]
Hi @zeeshanali, thanks for taking the time to report this issue to us.

I believe it was a momentary outage from the Labix Blog as it's up and working now.
