### ISSUE TITLE
Dead URL

### ISSUE THREAD

**Issue by zeeshanali** [canonical-web-and-design/juju.is#387]
A good number of [tutorials and explanations](https://juju.is/tutorials) about Charmed Operators (“charms”) exist already. And recently, a [workshop session]() has been given by  

This Workshop session link is not working . seems dead link

**Comment by anthonydillon** [comment]
Hi @zeeshanali, could you highlight the broken link you mean? All tutorials seen to be working for me.

**Comment by zeeshanali** [comment]
actually  when you go to page https://juju.is/tutorials/build-and-deploy-mini-charm#1-introduction   the Workshop session is hyperlinked to none.. this has to be removed .

**Comment by zeeshanali** [comment]
Can i pull request to do the code change as part of onboarding at canonical ?

**Comment by anthonydillon** [comment]
@zeeshanali Sure thing! although in this case, it would be editing a discourse post which you should be able to do. Follow the[Suggest changes ›](https://discourse.jujucharms.com/t/building-and-deploying-a-mini-charm/5512) link the bottom of the content to land on the topic. All the tutorial content is loaded from there.

**Comment by zeeshanali** [comment]
aha is this also running on discourse ?

**Comment by zeeshanali** [comment]
sorry i mean this one https://charmed-kubeflow.io/docs/install

**Comment by anthonydillon** [comment]
The link has been fixed.
