### ISSUE TITLE
Wrong url link 404 error

### ISSUE THREAD

**Issue by zeeshanali** [canonical-web-and-design/juju.is#388]
Source: https://juju.is/docs/olm/get-started-charmed-kubernetes

Go to bottom 
Learn more about Charmed Kubernetes  <--- link to Charmed Kubernetes metnioned https://charmhub.io/kubernetes  which is 404 error

**Comment by anthonydillon** [comment]
@zeeshanali thank you very much for taking the time to report this broken link. I have removed this one as we no longer have a specific Kubernetes topic page. I further improved in links and content in the last section.
