### ISSUE TITLE
Dealing with inert credentials link doesn't work

### ISSUE THREAD

**Issue by radraw** [canonical-web-and-design/juju.is#39]
Link following link doesn't work (404 response): 

https://juju.is/t/tutorial-managing-credentials/1289#heading--dealing-with-inert-credentials#heading--dealing-with-inert-credentials

**Comment by timClicks** [comment]
Hi @radraw do you know where you found that link?

**Comment by radraw** [comment]
I'm sorry I didn't provide such information. Now I don't remember, it had
to be some tutorial page.

czw., 16 kwi 2020 o 06:49 Tim McNamara <notifications@github.com>
napisał(a):

**Comment by barrymcgee** [comment]
@radraw The correct link is:

https://juju.is/docs/t/tutorial-managing-credentials/1289#heading--dealing-with-inert-credentials

I've tried to search for the broken link across the web but to no avail. If you come across this broken link again, please let us know where you found it and we'll get it fixed up if it's within our control.
