### ISSUE TITLE
Latest blog posts are not visible on blog homepage

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/juju.is#396]
Eg. https://juju.is/blog doesn't contain https://juju.is/blog/the-operator-day-industry-panel-at-kubecon-eu-2022 , which by virtue of date should be visible.

**Comment by anthonydillon** [comment]
It visible in the top section:
![image](https://user-images.githubusercontent.com/1413534/167940714-1e35d10a-c50a-4b11-9988-bce4369ae69a.png)

If you want it to be highlighted you need to make it sticky.

**Comment by mcjaeger** [comment]
@anthonydillon I am sorry but I still see an issue. The teasers in the upper right area work, but the main list section lists blog posts only until Sept 17th 2021. This area lists 23 blog posts on 3 pages (first page 9, next page) and this one is missing in this list (I tried with two blog posts with the tag for juju.is):

http://ubuntu.com/blog/software-operator-design-pattern-part-1

https://juju.is/blog/software-operator-design-pattern-part-1

**Comment by anthonydillon** [comment]
Reopening after more information is given. This needs further investigation.

**Comment by jkfran** [comment]
Hi, can someone explain what is the issue here?

**Comment by mcjaeger** [comment]
The blog post:
https://ubuntu.com/blog/operator-day-at-kubecon-eu-2022-recordings
Should be also visible here:
https://juju.is/blog
but is currently not. The blog has the same tags, as e.g.,
https://juju.is/blog/software-operator-design-pattern-part-4
