### ISSUE TITLE
Odd spacing after a main list item, but only sometimes

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#411]
This behaves as expected:

![image](https://user-images.githubusercontent.com/38667005/172410324-c91704f1-1b67-4101-8544-2b548ff39249.png)
 
This has weird vertical space between the top list item and the nested list:
![image](https://user-images.githubusercontent.com/38667005/172410386-7d0e0c71-5f20-4fc7-9380-f1118fb9933c.png)

https://juju.is/docs/olm/how-to
https://discourse.charmhub.io/t/olm-how-to-guides/5334

**Comment by anthonydillon** [comment]
I switched the markdown from (*) to (-) and (+), both of which work as expected. We render the markup generated by discourse directly. 

My guess is that this could be a bug in the discourse list renderer which is confusing a list item with a bold element and creating a paragraph element. 

Happy to dig deeper if you need to use (*) for lists. But will close for not but please comment and reopen if you would like more investigation.

**Comment by tmihoc** [comment]
I actually tried both (*) ad (-). The result looked the same to me, namely, as above.

**Comment by tmihoc** [comment]
I actually tried both (*) ad (-). The result looked the same to me, namely, as above.

**Comment by tmihoc** [comment]
@anthonydillon I just noticed the oddest thing on the page below (website and Discourse link): If I alternative - and + for the main list items, the odd spacing goes away. That's actually the _only_ way it goes away.

https://juju.is/docs/olm/how-to?dfgh
https://discourse.charmhub.io/t/olm-how-to-guides/5334

**Comment by anthonydillon** [comment]
This is very strange. It is probably worth creating an example page for this on a staff post to test alternatives and try to discover the reason. Resulting in an issue upstream.
