### ISSUE TITLE
[UX Review] Revise "benefit strip" design on Juju index

### ISSUE THREAD

**Issue by davegoddard42** [canonical-web-and-design/juju.is#412]
Edit this so that it doesn't get cut off mid-way through a sentence/image. Share with stakeholders for feedback

![image.png](https://images.zenhubusercontent.com/609106f0180d4707d2eed75a/90b659d2-5a64-4a53-a915-075263977319)

**Comment by anasereijo** [comment]
Hey @davegoddard42
I think it works really well! 

Thanks for sharing this.

**Comment by anasereijo** [comment]
@davegoddard42 I see a QA review is pending for this to be completed. Who would you like to assign this to?

**Comment by davegoddard42** [comment]
@anasereijo - sorry, on holiday. I need PM approval, I'm speaking to Michael and Holly about it - I'll update today. I normally put the PdM review tag on these but I don't think the Marketplace repo has that label.

**Comment by anasereijo** [comment]
@davegoddard42 I just added the label for you :)
