### ISSUE TITLE
Side navigation in docs can't be opened on mobile

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/juju.is#42]
Side navigation in juju.is/docs gets hidden on mobile, but it can't be expanded. It seems like menu button under search doesn't do anything.

<img width="516" alt="Screenshot 2020-03-31 at 11 33 51" src="https://user-images.githubusercontent.com/83575/78011361-c696dc00-7343-11ea-9581-f581fe834237.png">

**Comment by clagom** [comment]
Thanks @bartaz this seems a bug, but I think other than fixing this we then need to work on a better mobile experience for navigation and table of content (CC @cristinadresch this would be across UX).

**Comment by bartaz** [comment]
@clagom Sure, I think this iteration design work seems related: https://github.com/canonical-web-and-design/vanilla-framework/issues/2920 as we are going to figure out how side navigation should behave on mobile
