### ISSUE TITLE
Navigation doesn't match anchor on discourse

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/juju.is#47]
![Screen Shot 2020-04-08 at 9 21 13 AM](https://user-images.githubusercontent.com/532033/78802719-5f98a900-797b-11ea-8b52-d049f66b7620.png)

If you hover over this icon on discourse.juju.is it'll show the link "https://discourse.juju.is" but clicking it takes you to "https://juju.is".

**Comment by howbazaar** [comment]
@anthonydillon not sure who changed the header here, but it needs updating. Has confused me and @wallyworld too

**Comment by anthonydillon** [comment]
Thanks for the feedback. 

The reason for the change of link is to replicate a cohesive site between the marketing and discourse. The main logo goes to the homepage of the marketing site as it does in all cases. If you visit discourse and want to go to the homepage of discourse please hit the discourse link again. As you would if discourse was a subpage of the entire site.

I have updated the `href` to reflect where you will actually end up so I hope that removed the confusion.

**Comment by anthonydillon** [comment]
If not, reopen and I will address the concerns further.
