### ISSUE TITLE
Incomplete sentence on https://juju.is/docs/microk8s-cloud

### ISSUE THREAD

**Issue by davecore82** [canonical-web-and-design/juju.is#48]
There's an incomplete sentence in this paragraph:

> Important concept - clouds registered on the controller vs the client: Clouds are deployment targets. They include credential information. Your controller can be notified of new clouds, allowing
>

**Comment by anthonydillon** [comment]
@davecore82 thank you for taking the time to report this issue. We will try and fix this as quickly as possible.

**Comment by anthonydillon** [comment]
@timClicks would you mind taking a look into this please.

**Comment by timClicks** [comment]
Thanks @davecore82. Fixed. The sidebar now reads as:

>  **Important concept - clouds:**
>
> A cloud, as a Juju term, means a deployment target. A cloud includes API endpoints and credential information.
> 
> In Juju, you interact with the client (the juju command on your local machine). It connects to a controller. The controller is hosted on a cloud and controls models.
>
> A cloud can be registered on the controller, the client or both. Registering a cloud with the client allows the client to bootstrap a new controller onto it. Registering a cloud with a controller allows it to control models hosted on multiple providers.

**Comment by anthonydillon** [comment]
Thanks @timClicks
