### ISSUE TITLE
Can't direct a tutorial to be hosted at juju.is/tutorials

### ISSUE THREAD

**Issue by timClicks** [canonical-web-and-design/juju.is#49]
I'm in the process of [writing a tutorial for the Juju community](https://discourse.juju.is/t/how-to-self-host-nextcloud-and-collabora-on-ubuntu-server-both-backed-by-https-provided-by-lets-encrypt/2116), but can't figure out how to send it to juju.is/tutorials rather than jaas.ai/tutorials where it currently appears.

**Comment by anthonydillon** [comment]
Thanks for the nudge @timClicks. We have forgetten to implement the modern tutorials system into juju.is. Will work on that now.
