### ISSUE TITLE
Search clear button is misplaced

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/juju.is#55]
Firefox 75.0, Chromium 65.0

1\. Go to [juju.is/docs](https://juju.is/docs).
2\. Type anything in the search field.

What you see: The clear button is
- 11.3rem from the right edge of the field (`.p-search-box__input {padding-right: calc(2 * 2.3rem)` + `<button style="right: 6.7rem">`)
- slightly above the vertical center of the field.

![image](https://user-images.githubusercontent.com/19801137/80709117-b01ba600-8ae4-11ea-97cd-f9878157ced7.png)

What you should see: The clear button should be
- only a few pixels from the right edge of the field
- vertically centered in the field.

A similarly misplaced clear button appeared on ubuntu.com in January ([ubuntu.com#6472](https://github.com/canonical-web-and-design/ubuntu.com/issues/6472)).

**Comment by hatched** [comment]
This has been resolved.
