### ISSUE TITLE
Search not working properly

### ISSUE THREAD

**Issue by facundobatista** [canonical-web-and-design/juju.is#63]
If I go to juju.is/docs and search 'status-set', I get 10 results.

10 different results, pointing to 10 different pages... but somehow 9 of those results all have the same title, "The simplest way to deploy and maintain applications in the ... - Juju".

But, more importantly, in all those 10 pages, the string 'status-set' is NOT THERE.

None of those 10 results pointed me to https://discourse.juju.is/t/hook-tools/1163 (which is where status-set is documented, I later found).

**Comment by anthonydillon** [comment]
You can use: "status-set". Does this solve the issue for you.
