### ISSUE TITLE
Docs, mobile UI overlapping search input over button

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/juju.is#65]
![image](https://user-images.githubusercontent.com/1953388/82586104-f10c5500-9b8e-11ea-8f68-69ca642640d5.jpeg)

There seems to be a button under the input search field, barely visible. Would be enough to align this with the other docs pages (e.g. on maas.io) without button.

**Comment by anthonydillon** [comment]
It looks like the mark up is just out of date from Vanilla. The button is the search button.

**Comment by barrymcgee** [comment]
Nice 👌🏻
