### ISSUE TITLE
dead link as "Dealing with inert credentials"

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/juju.is#74]
The link with the text "Dealing with inert credentials" in
https://juju.is/docs/vsphere-cloud#heading--adding-credentials
leads to:
https://juju.is/t/tutorial-managing-credentials/1289#heading--dealing-with-inert-credentials#heading--dealing-with-inert-credentials
but it's 404 Not Found.

![Screenshot from 2020-06-18 00-01-50](https://user-images.githubusercontent.com/4356209/84914753-f1006600-b0f6-11ea-9031-f173de69b45d.png)

**Comment by anthonydillon** [comment]
@nobuto-m thank you for taking the time to report this issue. The page has been fixed.
