### ISSUE TITLE
Every docs page has the title "Juju - The simplest way to deploy and maintain applications in the cloud"

### ISSUE THREAD

**Issue by timClicks** [canonical-web-and-design/juju.is#79]
Every document within docs has the same title. Although it's parameterised within the template, it looks like something's not set correctly..

https://github.com/canonical-web-and-design/juju.is/blob/fb98983e0c9a0037b497ac540330714a999ebde3/templates/docs/base.html#L4

Related issue https://github.com/juju/docs/issues/3482

**Comment by barrymcgee** [comment]
This is now resolved.
