### ISSUE TITLE
Copy code snippet - remove copy-icon and border

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/juju.is#9]
From juju.is, will be proposed on Vanilla as an optional UI element instead of the current one.
Remove the border, leave a white background (on grey) or a grey background if the snippet is on white.

E.g.:
![Screenshot 2019-10-31 at 14.32.49.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/d132f771-43ef-42e3-a377-2ec592eeaf1a)

![Screenshot 2019-10-31 at 15.30.12.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/7f8b0d15-7b16-4d1a-8a73-79e8671efc64)

For all, remove the copy icon and copy functionality on click.

**Comment by cristinadresch** [comment]
@anthonydillon you're ok to finish this before the jaas call tomorrow?

**Comment by anthonydillon** [comment]
@cristinadresch I've done it and its in for review above ^
