### ISSUE TITLE
link to help-google doesn't work

### ISSUE THREAD

**Issue by mastier** [canonical-web-and-design/juju.is#93]
is listed in wizard for running deployment
https://jujucharms.com/docs/stable/help-google
![image](https://user-images.githubusercontent.com/1609672/92519916-12b34a00-f21b-11ea-9e64-e52f3b1a8939.png)
Under "setting up GCE credentials"

**Comment by hatched** [comment]
Thanks for filing the issue, the application you're using there is an old version of the UI which is currently in maintenance-only mode and will be taken down in the near future.

The new UI is more focused on monitoring and operations at jaas.ai/models.

We now recommend using the CLI for bootstrap and deployment operations https://juju.is/docs/getting-started-with-juju
